table:
  name: product_option_values
  schema: inventory
object_relationships:
  - name: product
    using:
      manual_configuration:
        column_mapping:
          product_id: id
        insertion_order: null
        remote_table:
          name: products
          schema: inventory
  - name: product_option_type
    using:
      manual_configuration:
        column_mapping:
          product_id: product_id
        insertion_order: null
        remote_table:
          name: product_option_types
          schema: inventory
